import {SelectItem} from 'primeng/api';

export const RASHIS = [
  {label: 'Mesha', value: '1'},
  {label: 'Vrushaba', value: '2'},
  {label: 'Mithuna', value: '3'},
  {label: 'Kataka', value: '4'},
  {label: 'Simha', value: '5'},
  {label: 'Kanya', value: '6'},
  {label: 'Tula', value: '7'},
  {label: 'Vrushchika', value: '8'},
  {label: 'Dhanash', value: '9'},
  {label: 'Makara', value: '10'},
  {label: 'Kumba', value: '11'},
  {label: 'Meena', value: '12'},
];

export const NAKSHATRAS: SelectItem[] = [
  {label: 'Ashwini', value: '1'},
  {label: 'Bharani', value: '2'},
  {label: 'Kruthika', value: '3'},
  {label: 'Rohini', value: '4'},
  {label: 'Mrugasira', value: '5'},
  {label: 'Aarudhra', value: '6'},
  {label: 'Punarvasu', value: '7'},
  {label: 'Pushya', value: '8'},
  {label: 'Aashlesha', value: '9'},
  {label: 'Makha', value: '10'},
  {label: 'Pubba', value: '11'},
  {label: 'Uttara', value: '12'},
  {label: 'Hastha', value: '13'},
  {label: 'Chittha', value: '14'},
  {label: 'Swathi', value: '15'},
  {label: 'Vishaka', value: '16'},
  {label: 'Anuradha', value: '17'},
  {label: 'Jayeshta', value: '18'},
  {label: 'Moola', value: '19'},
  {label: 'Purvashada', value: '20'},
  {label: 'Uttarashada', value: '21'},
  {label: 'Sravana', value: '22'},
  {label: 'Dhanishta', value: '23'},
  {label: 'Shatabisha', value: '24'},
  {label: 'Purvabhadra', value: '25'},
  {label: 'Uttarabhadra', value: '26'},
  {label: 'Revathi', value: '27'}
];

export const LAGNAS: SelectItem[] = [
  {label: 'Mesha', value: '1'},
  {label: 'Vrushaba', value: '2'},
  {label: 'Mithuna', value: '3'},
  {label: 'Kataka', value: '4'},
  {label: 'Simha', value: '5'},
  {label: 'Kanya', value: '6'},
  {label: 'Tula', value: '7'},
  {label: 'Vrushchika', value: '8'},
  {label: 'Dhanash', value: '9'},
  {label: 'Makara', value: '10'},
  {label: 'Kumba', value: '11'},
  {label: 'Meena', value: '12'},
];

export const THITHIS = [
  {label: 'Shukla Paksha - Padyami', value: '1'},
  {label: 'Shukla Paksha - Dwithiya', value: '2'},
  {label: 'Shukla Paksha - Thrithiya', value: '3'},
  {label: 'Shukla Paksha - Chaturthi', value: '4'},
  {label: 'Shukla Paksha - Panchami', value: '5'},
  {label: 'Shukla Paksha - Shahsti', value: '6'},
  {label: 'Shukla Paksha - Sapthami', value: '7'},
  {label: 'Shukla Paksha - Ashtami', value: '8'},
  {label: 'Shukla Paksha - Navami', value: '9'},
  {label: 'Shukla Paksha - Dashami', value: '10'},
  {label: 'Shukla Paksha - Ekadashi', value: '11'},
  {label: 'Shukla Paksha - Dwadasi', value: '12'},
  {label: 'Shukla Paksha - Trayodasi', value: '13'},
  {label: 'Shukla Paksha - Chathurdasi', value: '14'},
  {label: 'Shukla Paksha - Poornima', value: '15'},
  {label: 'Krishna Paksha - Padyami', value: '16'},
  {label: 'Krishna Paksha - Dwithiya', value: '17'},
  {label: 'Krishna Paksha - Thrithiya', value: '18'},
  {label: 'Krishna Paksha - Chaturthi', value: '19'},
  {label: 'Krishna Paksha - Panchami', value: '20'},
  {label: 'Krishna Paksha - Shahsti', value: '21'},
  {label: 'Krishna Paksha - Sapthami', value: '22'},
  {label: 'Krishna Paksha - Ashtami', value: '23'},
  {label: 'Krishna Paksha - Navami', value: '24'},
  {label: 'Krishna Paksha - Dashami', value: '25'},
  {label: 'Krishna Paksha - Ekadashi', value: '26'},
  {label: 'Krishna Paksha - Dwadasi', value: '27'},
  {label: 'Krishna Paksha - Trayodasi', value: '28'},
  {label: 'Krishna Paksha - Chathurdasi', value: '29'},
  {label: 'Krishna Paksha - Poornima', value: '30'}
];

export const DAYS = [
  {label: 'Sunday', value: '1'},
  {label: 'Monday', value: '2'},
  {label: 'Tuesday', value: '3'},
  {label: 'Wednesday', value: '4'},
  {label: 'Thursday', value: '5'},
  {label: 'Friday', value: '6'},
  {label: 'Saturday', value: '7'},
];

export const TARABALA_RESULT = [
  {label: 'Parama Mythra Thaare - Neutral', value: 0},
  {label: 'Janma Thaare - Shaaka dhaana(Tarkari)', value: 1},
  {label: 'Sampath Thaare - Good', value: 2},
  {label: 'Vipath Thaare - Bella dhaana', value: 3},
  {label: 'Kshema Thaare - Good', value: 4},
  {label: 'Pratyarukh Thaare - Uppu dhaana', value: 5},
  {label: 'Saadhaka Thaare - Good', value: 6},
  {label: 'Vadha Thaare - Not Good - Yellu, Chinna, Vastra', value: 7},
  {label: 'Mitra Thaare - Good', value: 8}
];

export const CHANDRABALA_RESULT = [
  {label: 'Good - Deha Soukhya', value: 1},
  {label: 'Bad - Kalaha - Chandragraha pooje, Chandramantra japa, Akki dhana', value: 2},
  {label: 'Good - Dhravya Labha', value: 3},
  {label: 'Bad - Rogha Bhaya - Chandragraha pooje, Chandramantra japa, Akki dhana', value: 4},
  {label: 'Bad - Karya Vikalpa - Chandragraha pooje, Chandramantra japa, Akki dhana', value: 5},
  {label: 'Bad - Shatru Nasha - Chandragraha pooje, Chandramantra japa, Akki dhana', value: 6},
  {label: 'Good - Soukhya Vrudhi', value: 7},
  {label: 'Good - Arogya Vrudhi', value: 8},
  {label: 'Bad - Karya Tamasa - Chandragraha pooje, Chandramantra japa, Akki dhana', value: 9},
  {label: 'Good - Udhyoga Vrudhi', value: 10},
  {label: 'Good - Istartha Siddhi', value: 11},
  {label: 'Bad - Dhana Vyeya - Chandragraha pooje, Chandramantra japa, Akki dhana', value: 12},
];

export const GURUBALA_RESULT = [
  {label: 'No Gurubala', value: 1},
  {label: 'Good - Gurubala Present', value: 2},
  {label: 'No Gurubala', value: 3},
  {label: 'No Gurubala', value: 4},
  {label: 'Good - Gurubala Present', value: 5},
  {label: 'No Gurubala', value: 6},
  {label: 'Good - Gurubala Present', value: 7},
  {label: 'No Gurubala', value: 8},
  {label: 'Good - Gurubala Present', value: 9},
  {label: 'No Gurubala', value: 10},
  {label: 'Good - Gurubala Present', value: 11},
  {label: 'No Gurubala', value: 12},
];
