export const RASHIS = [
  {label: 'Mesha', value: '1'},
  {label: 'Vrushaba', value: '2'},
  {label: 'Mithuna', value: '3'},
  {label: 'Kataka', value: '4'},
  {label: 'Simha', value: '5'},
  {label: 'Kanya', value: '6'},
  {label: 'Tula', value: '7'},
  {label: 'Vrushchika', value: '8'},
  {label: 'Dhanash', value: '9'},
  {label: 'Makara', value: '10'},
  {label: 'Kumba', value: '11'},
  {label: 'Meena', value: '12'},
];

export const NAKSHATRAS = [
  {label: 'Ashwini', value: '1'},
  {label: 'Bharani', value: '2'},
  {label: 'Kruthika', value: '3'},
  {label: 'Rohini', value: '4'},
  {label: 'Mrugasira', value: '5'},
  {label: 'Aarudhra', value: '6'},
  {label: 'Punarvasu', value: '7'},
  {label: 'Pushya', value: '8'},
  {label: 'Aashlesha', value: '9'},
  {label: 'Makha', value: '10'},
  {label: 'Pubba', value: '11'},
  {label: 'Uttara', value: '12'},
  {label: 'Hastha', value: '13'},
  {label: 'Chittha', value: '14'},
  {label: 'Swathi', value: '15'},
  {label: 'Vishaka', value: '16'},
  {label: 'Anuradha', value: '17'},
  {label: 'Jayeshta', value: '18'},
  {label: 'Moola', value: '19'},
  {label: 'Purvashada', value: '20'},
  {label: 'Uttarashada', value: '21'},
  {label: 'Sravana', value: '22'},
  {label: 'Dhanishta', value: '23'},
  {label: 'Shatabisha', value: '24'},
  {label: 'Purvabhadra', value: '25'},
  {label: 'Uttarabhadra', value: '26'},
  {label: 'Revathi', value: '27'}
];

export const LAGNAS = [
  {label: 'Mesha', value: '1'},
  {label: 'Vrushaba', value: '2'},
  {label: 'Mithuna', value: '3'},
  {label: 'Kataka', value: '4'},
  {label: 'Simha', value: '5'},
  {label: 'Kanya', value: '6'},
  {label: 'Tula', value: '7'},
  {label: 'Vrushchika', value: '8'},
  {label: 'Dhanash', value: '9'},
  {label: 'Makara', value: '10'},
  {label: 'Kumba', value: '11'},
  {label: 'Meena', value: '12'},
];

export const TARABALA_RESULT = [
  {label: 'Parama Mythra Taare - Neutral', value: 0},
  {label: 'Janma Taare - Shaaka dhaana(Tarkari)', value: 1},
  {label: 'Sampath Taare - Good', value: 2},
  {label: 'Vipath Taare - Bella dhaana', value: 3},
  {label: 'Kshema Taare - Good', value: 4},
  {label: 'Pratyarukh Taare - Uppu dhaana', value: 5},
  {label: 'Saadhaka Taare - Good', value: 6},
  {label: 'Vadha Taare - Not Good - Yellu, Chinna, Vastra', value: 7},
  {label: 'Mitra Taare - Good', value: 8}
];
